/** Tabela para registro de segurança e acesso ao consumir o WS -> integraTotem **/

DROP SEQUENCE S_TB_ACESSO;
CREATE SEQUENCE S_TB_ACESSO;

DROP TABLE TB_ACESSO;

CREATE TABLE TB_ACESSO(

	ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('S_TB_ACESSO'),
	HASH BIGINT NOT NULL,
	CHAVE VARCHAR(30),
	DATA_ACESSO TIMESTAMP
);

DROP INDEX I_TB_ACESSO_HASH_CHAVE;
CREATE INDEX I_TB_ACESSO_HASH_CHAVE ON TB_ACESSO(HASH, CHAVE);

SELECT * 
FROM TB_ACESSO;

SELECT count(*) 
FROM TB_ACESSO;


DELETE FROM TB_ACESSO;